apiVersion: v1
kind: Service
metadata:
  name: boston123-service
spec:
  selector:
    app: "boston123"
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "boston123"
spec:
  selector:
    matchLabels:
      app: "boston123"
  replicas: 1
  template:
    metadata:
      labels:
        app: "boston123"
    spec:
      containers:
      - name: "boston123"
        image: "boston123:latest"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80